[package]
name = "common"
version = "0.2.0"
description = "Antelope Common Substream"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
substreams = { workspace = true }
substreams-antelope = { workspace = true }
