[package]
name = "params"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
# substreams = { workspace = true }
substreams = { path = "/Users/denis/Github/substreams-rs/substreams"}