[package]
name = "eosio_ibc"
version = "0.4.0"
description = "Antelope [eosio.ibc] Substream"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
prost = "0.11"
prost-types = "0.11"
substreams = { workspace = true }
substreams-antelope-core = { workspace = true }
