[workspace]
members = [
    "substreams/*",
]

[workspace.dependencies]
substreams = "0.5.0"
substreams-antelope = "0.1"

[build]
target = "wasm32-unknown-unknown"

[profile.release]
lto = true
opt-level = 's'
strip = "debuginfo"
